### ISSUE TITLE
Parse error when inf present in DOM dump json

### ISSUE THREAD

**Issue by hariharanweb** [moredip/Frank#110]
Hi,

I found that symbiote throws are json parse error when there are some elements on screen with inf values...

eg: "origin":{"x":inf,"y":inf}

think the inf should be replaced with some value.

Thanks
Hari

**Comment by moredip** [comment]
I believe this issue has been resolved for a while now.

What version of Frank are you using? Also did you update libFrank.a if/when you updated the frank-cucumber gem?

**Comment by hariharanweb** [comment]
I am currently using frank-cucumber - 0.9.4....
I did update my frank gem and I ran frank-skeleton update.. It did say libFrank.a was identical...
Though I manually copied the /Library/Ruby/Gems/1.8/gems/frank-cucumber-0.9.4/frank-skeleton/libFrank.a to my project and built it again...
But I still get the parse error still...

**Comment by moredip** [comment]
Can you provide any more detail on what views are causing this issue? Can you take a look at the raw JSON being returned from http://localhost:37265/dump and see if there's a specific type of view that has these values?

**Comment by moredip** [comment]
This was resolved as of Frank 1.1.0.

**Comment by tapi** [comment]
I'm appear to be seeing the same issue with Frank v1.1.3, i've tried to dig around in the code and see where might be the best place/way to handle it.

I am able to see inf in the JSON displayed at http://localhost:37265/dump

The class is MPVolume Slider

The console error isnt too helpful, just says 
    Failed while talking to Frank. [Object, "parsererror", SyntaxError]
